### ISSUE TITLE
Browser used for view/blame/history is no longer the system default

### ISSUE THREAD

**Issue by daveFNbuck** [bgreenlee/sublime-github#111] opened 2017-06-05 18:35 UTC
About a week ago the plugin just decided to start using Firefox rather than my system default of Chrome to open these links on my work computer. On my personal laptop they don't do anything at all. I'm using build 3126 on macOS Sierra 10.12.5

**Comment by cletusw** [comment] 2017-06-05 20:20
This is happening for me also. Also started just recently. Build 3126 on macOS 10.12.5 for me as well.

**Comment by cshold** [comment] 2017-06-06 17:17
+1

**Comment by cletusw** [comment] 2017-06-06 17:21
@daveFNbuck @cshold Looks like this was caused by https://github.com/SublimeTextIssues/Core/issues/1714 which is fixed in build 3133 (get it using the dev builds [here](https://www.sublimetext.com/3dev)), so this issue can probably be closed. At least, it fixed the issue for me.

**Comment by cshold** [comment] 2017-06-06 17:25
Awesome, thanks for the prompt response, and for contributing to this awesome helper

**Closed** 2017-06-06 18:26 UTC
